### ISSUE TITLE
I have some issues.

### ISSUE THREAD

**Issue by wanghy921** [Tappai/PV_prediction#2]
BP test：TypeError: linear(): argument 'input' (position 1) must be Tensor, not DataFrame
Bi lstm test：RuntimeError: input.size(-1) must be equal to input_size. Expected 4, got 7

**Comment by Urazome2021** [comment]
i have the same questions. i don't know how to change the second question and i want to know only one question in the Bi-lstm-test. can you help me? Thank you

**Comment by wanghy921** [comment]
I am not the author of this project, but I think I understand the code, if you have questions you can ask me。Bi-LSTM is not different from the other three, the training code is the same, and the final result is normal








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tappat225/PV_prediction"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月16日(星期二) 晚上9:59
***@***.***&gt;;
抄送:&nbsp;"Grasp the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [tappat225/PV_prediction] I have some issues. (Issue #2)





 
i have the same questions. i don't know how to change the second question and i want to know only one question in the Bi-lstm-test. can you help me? Thank you

**Comment by Urazome2021** [comment]
谢谢你的帮助，我想问一下，就是在bilstm_test的时候，哪个参数控制input.size，也就是说，如何修改使得got4，请您有时间了帮忙解答一下。

**Comment by Urazome2021** [comment]
Thank you for your help, I would like to ask, which parameter controls input.size in Bi lstm test, that is, how to modify it to make got4, please help to answer when you have time.

**Comment by tappat225** [comment]
> Thank you for your help, I would like to ask, which parameter controls input.size in Bi lstm test, that is, how to modify it to make got4, please help to answer when you have time.

The problem is in the "input_feature", it should work now.

**Comment by Urazome2021** [comment]
May I ask if you are talking about the input_feature in the training module or the test module, I tried to modify the input_feature in the test, but it didn't work

**Comment by Urazome2021** [comment]
`input_feature = ['Wind_speed', 'Humidity', 'Temp', 'GHI']
input_feature_num = 4`
this？

**Comment by tappat225** [comment]
> May I ask if you are talking about the input_feature in the training module or the test module, I tried to modify the input_feature in the test, but it didn't work

Check out my latest commit.

**Comment by Urazome2021** [comment]
> > May I ask if you are talking about the input_feature in the training module or the test module, I tried to modify the input_feature in the test, but it didn't work
> 
> Check out my latest commit.

thanks for your help

**Comment by tappat225** [comment]
> > > May I ask if you are talking about the input_feature in the training module or the test module, I tried to modify the input_feature in the test, but it didn't work
> > 
> > 
> > Check out my latest commit.
> 
> thanks for your help

You're welcome.
